#!/bin/bash
rm "$HOME/output.html"
touch "$HOME/input"
touch "$HOME/.style.css"
cat<< EOF >"$HOME/.style.css"
* {font-size:16px;}
.background {margin:5rem 27.5rem 0rem 27.5rem;background-color:white;}
body {background-color:black;font-family:monospace;font-size:16px;border:1rem 1rem;padding:1rem 1rem;margin:1rem 1rem;}
.text {margin:2rem;}
b {color:blue;}
r {color:red;}
g {color:#00ff00;}
y {color:yellow;}
p {color:purple;}
o {color:orange;}
w {color:white;}
c {color:cyan;}
ooc {color:black;}
cc {color:#00827F;}
l {color:white;text-decoration:underline;}
l:hover {color:red;text-decoration:underline;font-style:italic;}
code {padding:1rem 1rem 1rem 1rem;color:rgb(98, 206, 88);justify-content:center}
pre {display:block;white-space:pre-wrap;width:100%;background-color:#141414;display:flex;border-style:inset;box-shadow:rgb(56, 29, 29);}
EOF
cat<< EOF >"$HOME/.input"
<html>
<head>
<link rel="stylesheet" href=".style.css">
<title>
</head>
<div class="background">
<h1>
<subtitle>
<body>
<div class="text">
<desc>                  
EOF
usage() {
    echo "Usage: $0 [path/to/file]"
}
if [ $# -gt 1 ]; then
    echo "Invalid number of options specified"
    usage
    exit 1
elif [ ! "$1" ]; then
    echo "You must provide a file!"
    usage
    exit 1
else
TITLE=$(sed -i -r "s'^(Title=)(.*)$'<title>\2</title>'g" "$@")
SUBTITLE=$(sed -i -r "s'^(Requires=)(.*)$'<subtitle>\2</subtitle>'g" "$@")
DESCRIPTION=$(sed -i -r "s'^(DESC=)(.*)$'<desc>\2</desc>'g" "$@")
grep --line-buffered '.*' "$1" >>"$HOME/.input"
sed -i -r "s'^(<h1>)$'<h1>$TITLE</h1>'g" "$@"
sed -i -r "s'^(<title>)$'"$TITLE"'g" "$HOME/.input"
sed -i -r "s'^(<subtitle>)$'"$SUBTITLE"'g" "$HOME/.input"
sed -i -r "s'^(<desc>)$'"$DESCRIPTION"'g" "$HOME/.input"
sed -i -r "s'^(blue |b ){1}(.*)$'<b>\2</b>'g" "$HOME/.input"
sed -i -r "s'^(red |r ){1}(.*)$'<r>\2</r>'g" "$HOME/.input"
sed -i -r "s'^(root ){1}(.*)$'<r>\$\2</r>'g" "$HOME/.input"
sed -i -r "s'^(green |g ){1}(.*)$'<g>\2</g>'g" "$HOME/.input"
sed -i -r "s'^(yellow |y ){1}(.*)$'<y>\2</y>'g" "$HOME/.input"
sed -i -r "s'^(purple |p ){1}(.*)$'<p>\2</p>'g" "$HOME/.input"
sed -i -r "s'^(orange |o ){1}(.*)$'<o>\2</o>'g" "$HOME/.input"
sed -i -r "s'^(white |w ){1}(.*)$'<w>\2</w>'g" "$HOME/.input"
sed -i -r "s'^(cyan |c ){1}(.*)$'<c>\2</c>'g" "$HOME/.input"
sed -i -r "s'^(link |l ){1}(.*)$'<g>\2</g>'g" "$HOME/.input"
sed -i -r "s'^(comment |cc ){1}(.*)$'<g>\2</g>'g" "$HOME/.input"
sed -i -r "s'^(CD){1}$'<pre><code>'g" "$HOME/.input"
sed -i -r "s'^(/DC){1}$'</code></pre>'g" "$HOME/.input"
sed -i -r "s'^(cc )(.*)$'<cc>\2</cc>'g" "$HOME/.input"
sed -i -r "s'^(\# )(.*)$'<cc>\1\2</cc>'g" "$HOME/.input"
echo -e " </div>\n </body>\n </div>\n </html>" >>"$HOME/.input"
cat "$HOME/.input">"$HOME/output.html" 
fi
rm "$HOME/.input"
